### PR TITLE
Burtbeckwith

### PR DESCRIPTION
**Pull request by jaGarcia**
Hi Burt.  I believe I've patched two bugs I encountered.  One, with a null session id (length=0) attempting to be invalidated, and a deserialization bug I encountered.

With the plugin as it stands with these patches, _knocks on every piece of wood in 20 foot radius_, I'm showing positive tests for persisted session support in Heroku w/ PostGres running two dynos..

### CODE REVIEW

**Comment by PatrickHuetter** [comment]
Hi jaGarcia, thanks for your work! Are there still any errors or problems left with this plugin and grails?

**Comment by jaGarcia** [comment]
The only one I've confirmed is this one:

http://jira.grails.org/browse/GPDATABASESESSION-5

It doesn't appear to be fatal, but is an anomaly. 

Other than that, I encountered a foreign key constraint violation when a session attribute was being inserted and I was initially concerned I had hit a locking/race condition.  But after create-drop'ing my test area, I can't reproduce it.  It's entirely likely that I had just corrupted my tables and hibernate_sequence object.

Perhaps it would be prudent to build in some exception handling to deal with bad sequence numbers....?  At the moment, I'm going to take my win and run for now.  I'll revisit it for sure if it pops it's head up again..

All this said, my tests last night on four dyno's in Heroku using PostGres was stable.  Tests = myself clearing cookies, not clearing cookies, Ctrl-R reloading, logging in and out a bunch of times.

**Comment by burtbeckwith** [comment]
Where is the fix for null session id?

**Comment by burtbeckwith** [comment]
I'm pretty sure that the null session id issue was fixed by https://github.com/burtbeckwith/grails-database-session/commit/61543c4f45a9463b3327bcba88d3744cdcfb715a

**Comment by jaGarcia** [comment]
Yeah, that's the same patch.  For some reason when I pulled from your repo the assignment of the session id variable patch wasn't in there (although the new cookie part was). 

Weird.  Anyhow, the deserialization was still occurring.  I haven't committed it yet, but I removed the maxsize 20000 constraint on the serialized attribute.

**Pull request merged**
