### PR TITLE
Two small fixes for an Exception and multiple cookies after a session is invalidated.

### PR DESCRIPTION
**Pull request by sronderos**
I was encountering two small issues with the plugin.

The first was that the first time I visited the application I would get
an AssertionFailed exception.  I believe this is because the null sessionId was being used for a call to invalidate().

17:34:33 web.1     | 2012-03-19 17:34:33,777 [qtp530654357-24 - /] ERROR databasesession.GormPersisterService  - [Assertion failed] - this String argument must have length; it must not be null or empty
17:34:33 web.1     | java.lang.IllegalArgumentException: [Assertion failed] - this String argument must have length; it must not be null or empty
17:34:33 web.1     |    at grails.plugin.databasesession.PersistentSessionAttributeValue.deleteBySessionId(PersistentSessionAttributeValue.groovy:45)
17:34:33 web.1     |    at grails.plugin.databasesession.GormPersisterService.invalidate(GormPersisterService.groovy:111)
17:34:33 web.1     |    at grails.plugin.databasesession.SessionProxyFilter.proxySession(SessionProxyFilter.java:90)
17:34:33 web.1     |    at grails.plugin.databasesession.SessionProxyFilter$1.getSession(SessionProxyFilter.java:42)
17:34:33 web.1     |    at grails.plugin.databasesession.SessionProxyFilter$1.getSession(SessionProxyFilter.java:47)

The second was that after a session was invalidated the application
would create a duplicate session cookie, causing my session information
to get lost.  This happened in Chrome, not sure if that had something
to do with it.  It should now ensure that the cookie that is returned
has the same path and host as the original cookie.

Also revved the version to the next micro plus snapshot.

### CODE REVIEW

**Comment by quorak** [comment]
+1

**Comment by quorak** [comment]
this plugin is not really usable. I always get the above mentioned exception. How can i get around it?
does this plugin also make the webflow plugin working across the heroku dynos?

**Comment by csherstan** [comment]
+1 completely unusable at this point :P

**Comment by carkar** [comment]
+1 works with above fixes

**Comment by PatrickHuetter** [comment]
It would be fine if Burt could integrate this fix into the main plugin. :-) And also this really good extended fork of the plugin: https://github.com/RobertFischer/grails-database-session

**Pull request merged**
